--SQL 함수

SELECT PLAYER_NAME FROM PLAYER WHERE ROWNUM <=1;

---
--문자형 함수
--FROM 절에 DUAL 입력해야함. (DUMMY 테이블)
SELECT LENGTH('SQL EXPERT') FROM DUAL;

DESC DUAL;
SELECT * FROM DUAL;

--CONCAT
SELECT CONCAT(PLAYER_NAME, '선수') 선수명 FROM PLAYER;

--날짜 함수
SELECT SYSDATE FROM DUAL;

EXTRACT(MONTH FROM HIREDATE) 입사월, EXTRACT(DAY FROM HIREDATE) 입사일 FROM EMP;


