
--PLAYER 테이블 생성

CREATE TABLE PLAYER(PLAYER_ID CHAR(7) NOT NULL
,PLAYER_NAME VARCHAR2(20) NOT NULL
,TEAM_ID CHAR(3) NOT NULL
,E_PLAYER_NAME VARCHAR2(40)
,NICKNAME VARCHAR2(30)
,JOIN_YYYY CHAR(4)
,POSITIONS VARCHAR2(10)
,BACK_NO NUMBER(3)
,NATION VARCHAR2(20)
,BIRTH_DATE DATE
,SOLAR CHAR(1)
,HEIGHT NUMBER(3)
,WEIGHT NUMBER(3)
,CONSTRAINT PLAYER_PK PRIMARY KEY (PLAYER_ID)) ;

--테이블 속성 조회
DESC PLAYER

SELECT * FROM PLAYER;

--TEAM 테이블 생성
CREATE TABLE TEAM ( TEAM_ID CHAR(3) NOT NULL, REGION_NAME VARCHAR2(8) NOT NULL, TEAM_NAME VARCHAR2(40) NOT NULL, E_TEAM_NAME VARCHAR2(50), ORIG_YYYY CHAR(4), STADIUM_ID CHAR(3) NOT NULL, ZIP_CODE1 CHAR(3), ZIP_CODE2 CHAR(3), ADDRESS VARCHAR2(80), DDD VARCHAR2(3), TEL VARCHAR2(10), FAX VARCHAR2(10), HOMEPAGE VARCHAR2(50), OWNER VARCHAR2(10), CONSTRAINT TEAM_PK PRIMARY KEY (TEAM_ID) );

--SELECT 문으로 테이블 TEMP 생성
CREATE TABLE TEAM_TEMP AS SELECT * FROM TEAM;

--새로운 컬럼 추가
ALTER TABLE PLAYER ADD (ADDRESS VARCHAR2(80));
DESC PLAYER;

--컬럼 제거
ALTER TABLE PLAYER DROP COLUMN ADDRESS;

--테이블 유형 변경

ALTER TABLE TEAM_TEMP MODIFY (ORIG_YYYY VARCHAR2(8) DEFAULT '20020129' NOT NULL);

DESC TEAM_TEMP;

ALTER TABLE PLAYER RENAME COLUMN PLAYER_ID TO TEMP_ID;
DESC PLAYER;
ALTER TABLE PLAYER RENAME COLUMN TEMP_ID TO PLAYER_ID;

--외래키 제약 조건 삭제 (원래 안만듬 이번엔)
ALTER TABLE PLAYER DROP CONSTRAINT PLAYER_FK;

--외래키 제약 조건 추가
ALTER TABLE PLAYER ADD CONSTRAINT PLAYER_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID);

--그럼 참조하는 TEAM 테이블은 삭제가 불가능
DROP TABLE TEAM;
--unique/primary keys in table referenced by foreign keys


